### PR TITLE
Fix Log4J initialization error

### PR DESCRIPTION
**Pull request by rsommerard**

### CODE REVIEW

**Comment by edwardcapriolo** [comment]
Yes. These messages are a bit annoying. What to you think about moving them to the debug level instead of setting them off?

**Comment by rsommerard** [comment]
I doubted about it and you're right, DEBUG level is surely better :+1:

**Comment by edwardcapriolo** [comment]
Great! So we agree. Lets use debug for normal operations, and only use logging for unexpected events. Please resubmit your PR after the changes and I will merge them.

**Comment by rsommerard** [comment]
I made it just above.

**Comment by edwardcapriolo** [comment]
I see what you did. My mistake, I might have been unclear. I think what we should do this is:

1) The project is missing a log4j file in src/main/resources. We should probably include one.
2) We should change the messages like "gossiper is starting" from level INFO to level debug
3) We should leave the project at level info

The reason I say this is because under normal operation this gossip library should probably produce no logging output. As it currently is now when I use this project in other projects I use it in unit tests and the console messages fill up my screen.

Are you ok with this?

**Comment by edwardcapriolo** [comment]
I fixed the logging here https://github.com/edwardcapriolo/gossip/commit/ca9c7c980980d3d9070aa7a09200c7cc7c4975a5 logging is at level debug. src/test/resources includes a log4j props presumably you would include your one in your own application.

**Pull request closed without merging**
